runtime: python37

entrypoint: gunicorn -b :$PORT main:app

# Update with Redis instance details
env_variables:
  REDISHOST: '10.167.246.123'
  REDISPORT: '6379'

# Update with Serverless VPC Access connector details
vpc_access_connector:
  name: projects/step-project-ellispis/locations/europe-west2/connectors/instance-1