"""
  Copyright 2020 Google LLC
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
"""

COLLECTION_IMAGES = 'ImagesTal'
# constant fields names:
COLLECTION_IMAGES_FIELD_INGESTED_PROVIDERS = 'ingestedProviders'
COLLECTION_IMAGES_FIELD_INGESTED_RUNS = 'ingestedRuns'
COLLECTION_IMAGES_FIELD_PROVIDER_ID = 'providerId'
COLLECTION_IMAGES_FIELD_COORDINATES = 'coordinates'
COLLECTION_IMAGES_FIELD_DATE_INGESTED = 'dateIngested'
COLLECTION_IMAGES_FIELD_DATE_SHOT = 'dateShot'
COLLECTION_IMAGES_FIELD_DATE_FIELDS = 'date'
COLLECTION_IMAGES_FIELD_IMAGE_ATTRIBUTES = 'imageAttributes'
COLLECTION_IMAGES_FIELD_FORMAT = 'format'
COLLECTION_IMAGES_FIELD_RESOLUTION = 'resolution'
COLLECTION_IMAGES_FIELD_WIDTH = 'width'
COLLECTION_IMAGES_FIELD_HEIGHT = 'height'
COLLECTION_IMAGES_FIELD_ATTRIBUTION = 'attribution'
COLLECTION_IMAGES_FIELD_LABELS = 'labels'
COLLECTION_IMAGES_FIELD_RANDOM = 'random'
COLLECTION_IMAGES_FIELD_URL = 'url'
COLLECTION_IMAGES_FIELD_HASHMAP = 'hashmap'
COLLECTION_IMAGES_FIELD_VISIBILITY = 'visibility'

COLLECTION_PIPELINE_RUNS = 'PipelineRuns'
# Constant field names:
COLLECTION_PIPELINE_RUNS_FIELD_PROVIDER_NAME = 'providerName'
COLLECTION_PIPELINE_RUNS_FIELD_PROVIDER_ID = 'providerId'
COLLECTION_PIPELINE_RUNS_FIELD_PROVIDER_VERSION = 'providerVersion'
COLLECTION_PIPELINE_RUNS_FIELD_PROVIDER_VISIBILITY = 'providerVisibility'
COLLECTION_PIPELINE_RUNS_FIELD_PIPELINE_RUN_ID = 'pipelineRunId'
COLLECTION_PIPELINE_RUNS_FIELD_START_DATE = 'startDate'
COLLECTION_PIPELINE_RUNS_FIELD_END_DATE = 'endDate'
COLLECTION_PIPELINE_RUNS_FIELD_VISIBILITY = 'visibility'

COLLECTION_IMAGE_PROVIDERS = 'ImageProviders'
COLLECTION_IMAGE_PROVIDERS_FIELD_API_KEY = 'api key'
COLLECTION_IMAGE_PROVIDERS_FIELD_SECRET_KEY = 'secret key'

COLLECTION_IMAGES_SUBCOLLECTION_PIPELINE_RUNS = 'PipelineRuns'
# Constant field names:
COLLECTION_IMAGES_SUBCOLLECTION_PIPELINE_RUNS_FIELD_PROVIDER_ID = 'providerId'
COLLECTION_IMAGES_SUBCOLLECTION_PIPELINE_RUNS_FIELD_PROVIDER_NAME = 'providerName'
COLLECTION_IMAGES_SUBCOLLECTION_PIPELINE_RUNS_FIELD_PROVIDER_VERSION = 'providerVersion'
COLLECTION_IMAGES_SUBCOLLECTION_PIPELINE_RUNS_FIELD_PARENT_IMAGE_ID = 'parentImageId'
COLLECTION_IMAGES_SUBCOLLECTION_PIPELINE_RUNS_FIELD_PIPELINE_RUN_ID = 'pipelineRunId'
COLLECTION_IMAGES_SUBCOLLECTION_PIPELINE_RUNS_FIELD_HASHMAP = 'hashmap'
COLLECTION_IMAGES_SUBCOLLECTION_PIPELINE_RUNS_FIELD_VISIBILITY = 'visibility'
COLLECTION_IMAGES_SUBCOLLECTION_PIPELINE_RUNS_FIELD_RANDOM = 'random'


COLLECTION_IMAGES_SUBCOLLECTION_LABELS = 'Labels'
# Constant field names:
COLLECTION_IMAGES_SUBCOLLECTION_LABELS_FIELD_PROVIDER_ID = 'providerId'
COLLECTION_IMAGES_SUBCOLLECTION_LABELS_FIELD_PROVIDER_VERSION = 'providerVersion'
COLLECTION_IMAGES_SUBCOLLECTION_LABELS_FIELD_LABEL_NAME = 'labelName'
COLLECTION_IMAGES_SUBCOLLECTION_LABELS_FIELD_LABEL_IDS = 'labelIds'
COLLECTION_IMAGES_SUBCOLLECTION_LABELS_FIELD_PARENT_IMAGE_ID = 'parentImageId'
COLLECTION_IMAGES_SUBCOLLECTION_LABELS_FIELD_PIPELINE_RUN_ID = 'pipelineRunId'
COLLECTION_IMAGES_SUBCOLLECTION_LABELS_FIELD_RANDOM = 'random'
COLLECTION_IMAGES_SUBCOLLECTION_LABELS_FIELD_HASHMAP = 'hashmap'
COLLECTION_IMAGES_SUBCOLLECTION_LABELS_FIELD_VISIBILITY = 'visibility'

COLLECTION_LABEL_TAGS = 'LabelTags'

COLLECTION_REDEFINE_MAPS = 'RedefineMaps'
# Constant field names:
COLLECTION_REDEFINE_MAPS_FIELD_REDEFINE_MAP = 'redefineMap'

# General:
LABEL_VISIBILITY_INVISIBLE  = 0
LABEL_VISIBILITY_VISIBLE  = 1
